### ISSUE TITLE
configure system-wide sender rewriting

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/ansible-role-postfix-mta#1]
http://www.postfix.org/ADDRESS_REWRITING_README.html#generic

from the docs:

>  Some hosts have no valid Internet domain name, and instead use a name such as localdomain.local. This can be a problem when you want to send mail over the Internet, because many mail servers reject mail addresses with invalid domain names.
> 
> With the smtp_generic_maps parameter you can specify generic(5) lookup tables that replace local mail addresses by valid Internet addresses when mail leaves the machine via SMTP. The generic(5) mapping replaces envelope and header addresses, and is non-recursive. It does not happen when you send mail between addresses on the local machine.
> 
> This feature is available in Postfix version 2.2 and later.
> 
> Example:
> 
>     /etc/postfix/main.cf:
>         smtp_generic_maps = hash:/etc/postfix/generic
> 
>     /etc/postfix/generic:
>         his@localdomain.local               hisaccount@hisisp.example
>         her@localdomain.local               heraccount@herisp.example
>         @localdomain.local                  hisaccount+local@hisisp.example

**Comment by codybennett** [comment]
Issue resolved with latest merge
